### ISSUE TITLE
UndefinedFunctionError at GET

### ISSUE THREAD

**Issue by jeroenbourgois** [talonframework/talon_demo#5]
Given a fresh install
When following the `/admin` route
I get the following error:

 ```
UndefinedFunctionError at GET /admin
function TalonDemo.Web.AdminController.init/1 is undefined (module TalonDemo.Web.AdminController is not available)
```
![image](https://user-images.githubusercontent.com/202312/27495124-ec3a80da-5850-11e7-98f1-8be3c6591293.png)

Thanks!

**Comment by smpallen99** [comment]
Project was out of date. Just updated it with latest master. Cloned a fresh version. Everything is working fine. Please test again and close the issue if working.

**Comment by jeroenbourgois** [comment]
Indeed it does!
